cookie:
  expiry_days: 2
  key: some_signature_key
  name: tulipauth
credentials:
  usernames:
    admin1:
      name: admin1
      password: $2b$12$XLJUl8l4YFf3gLN2b03P.uh67KxhIf4LyTVHMsy/oU9ODnLNmaNqO
      role: admin
      location: Delhi
    tulip:
      name: Tulip
      password: $2b$12$xtNDq.phIfDfCL/6DpmQ9u/76xDF3MicK5sPltwh6ZFQmfWQxyY6G
      role: master
      location: Mumbai
    user1:
      name: Rakesh
      password: $2b$12$2YtN.vfe1aPWy.nCANPzVepMU0HWxOr78ju/hzPQeguA0GEX75Kzi
      role: user
      location: Kota
