cookie:
  expiry_days: 2
  key: some_signature_key
  name: tulipauth
credentials:
  usernames:
    admin1:
      location: Pune
      name: admin1
      password: $2b$12$XLJUl8l4YFf3gLN2b03P.uh67KxhIf4LyTVHMsy/oU9ODnLNmaNqO
      role: admin
    tulip:
      location: Pune
      name: Tulip
      password: $2b$12$xtNDq.phIfDfCL/6DpmQ9u/76xDF3MicK5sPltwh6ZFQmfWQxyY6G
      role: master
    user1:
      location: Pune
      name: Rakesh
      password: $2b$12$2YtN.vfe1aPWy.nCANPzVepMU0HWxOr78ju/hzPQeguA0GEX75Kzi
      role: user
    user2:
      name: User2
      password: $2b$12$yXi73.06uvMgXO2mRqj8ku66dEB/xRIrTe.IX6FG.uJrR.zKvZA4O
      role: user
      location: Kota
    user3:
      name: User3
      password: $2b$12$8dFEsEwiQ9TFd3HNhurg/eSRqjCi26.SmFXabzwhanEcOLpvKNfU.
      role: user
      location: Bhopal
    user4:
      name: User4
      password: $2b$12$61vgYkKainDFPu9E1KsNGuWmZagW9cLiGYYic9zUKijiQHmzEfSD.
      role: user
      location: Kolkata
gst_number: 07AABCN8953B1ZI
